---
- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and dearmor Plex repository key
  ansible.builtin.get_url:
    url: "{{ plex_repo_key }}"
    dest: /etc/apt/keyrings/plexmediaserver.v2.gpg
    mode: '0644'

- name: Add Plex APT repository
  ansible.builtin.apt_repository:
    repo: "{{ debian_plex_repo_url }}"
    filename: plex
    state: present
    update_cache: yes

- name: Install Plex Server
  ansible.builtin.apt:
    name: plexmediaserver
    state: present
    update_cache: no
  notify:
    - Start and enable Plex service
