---
- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and dearmor Plex repository key
  ansible.builtin.get_url:
    url: "{{ plex_repo_key }}"
    dest: /etc/apt/keyrings/plexmediaserver.v2.gpg
    mode: '0644'

- name: Add Plex APT repository list file
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/plex.list
    content: "{{ debian_plex_repo_url }}\n"
    mode: '0644'

- name: Install Plex Server
  ansible.builtin.apt:
    name: plexmediaserver
    state: present
    update_cache: true
  notify:
    - Start and enable plexmediaserver

- name: Add ufw plex rule
  community.general.ufw:
    rule: allow
    port: "32400"
    proto: "tcp"
    state: enabled
