---
- name: Include APT tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Include DNF tasks
  ansible.builtin.include_tasks: el.yml
  when: ansible_facts['pkg_mgr'] == 'dnf'
