---
- name: Include APT tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Include DNF tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts['pkg_mgr'] == 'dnf'
