- name: Configure Plex repository
  ansible.builtin.template:
    src: plex.repo.j2
    dest: /etc/yum.repos.d/plex.repo
    mode: "0644"
- name: Clan yum repository
  ansible.builtin.command:
    cmd: sudo dnf clean all

- name: Refresh cache
  ansible.builtin.command:
    cmd: sudo dnf makecache -y

- name: Install Plex Server
  ansible.builtin.dnf:
    name: plexmediaserver
    state: present
  notify:
    - Start and enable Plex service
