---
- name: Configure Plex repository
  ansible.builtin.template:
    src: plex.repo.j2
    dest: /etc/yum.repos.d/plex.repo
    mode: "0644"
  register: plex_repo_template

- name: Clan yum repository
  ansible.builtin.command:
    cmd: sudo dnf clean all

- name: Refresh cache
  ansible.builtin.command:
    cmd: sudo dnf makecache -y

- name: Install Plex Server
  ansible.builtin.dnf:
    name: plexmediaserver
    state: present
    # Bypass the strict crypto validation block for the actual RPM signature match
    disable_gpg_check: true
    update_cache: "{{ plex_repo_template.changed }}"
  notify:
    - Reload systemd
    - Start and enable Plex service
