# -*- mode: ruby -*-
# vi: set ft=ruby :

# list of hosts
hosts = [
  { :name => "plex-ubuntu-24", :box => "bento/ubuntu-24.04" },
  { :name => "plex-alma-9",    :box => "almalinux/9" },
]

# configure Vagrant
Vagrant.configure("2") do |config|

  # loop through hosts
  hosts.each do |host|
    config.vm.define host[:name] do |instance|

      # general config
      instance.vm.box = host[:box]
      instance.vm.hostname = host[:name]

      # libvirt provider specific settings
      instance.vm.provider :libvirt do |libvirt|
        libvirt.memory = 2048
        libvirt.cpus = 2
      end

      # ansible config
      instance.vm.provision "ansible" do |ansible|
        ansible.playbook = "setup.yml"
        ansible.compatibility_mode = "2.0"
        ansible.verbose = false
      end

    end
  end

end