# -*- mode: ruby -*-
# vi: set ft=ruby :

# list of hosts
hosts = [
  { :name => "plex-ubuntu-22", :box => "ubuntu/jammy64" },
  { :name => "plex-ubuntu-24", :box => "ubuntu/noble64" },
  { :name => "plex-el-10",  :box => "centos/7" }
]

# configure Vagrant
Vagrant.configure("2") do |config|

  # loop through hosts
  hosts.each do |host|
    config.vm.define host[:name] do |instance|

      # general config
      instance.vm.box = host[:box]
      instance.vm.hostname = host[:name]

      # ansible config
      instance.vm.provision "ansible" do |ansible|
        ansible.playbook = "setup.yml"
        ansible.compatibility_mode = "2.0"
        ansible.verbose = false
      end

    end
  end

end