---
- name: Start and enable plexmediaserver
  ansible.builtin.systemd_service:
    name: plexmediaserver
    state: started
    enabled: true

- name: Restart plexmediaserver
  ansible.builtin.systemd_service:
    name: plexmediaserver
    state: restarted
